"""Path helpers for the autosetup output layout.

Each helper takes a `project_root` and returns a fully-qualified `Path` for
one well-known artifact. User-facing artifacts live under `certora/`;
intermediate machinery lives under `.certora_internal/`.
"""

from pathlib import Path

from certora_autosetup.utils.constants import (
    DIR_INTERNAL_CONFS,
    DIR_INTERNAL_DIFFICULT_RETRY,
    DIR_INTERNAL_MULTI_ASSERT,
    DIR_INTERNAL_ROUND_SUMMARIES,
    DIR_INTERNAL_SPECS,
    DIR_INTERNAL_TYPECHECKER_ROUNDS,
    DIR_USER_CERTORA,
    DIR_USER_CONFS,
    DIR_USER_HARNESSES,
    DIR_USER_SPECS,
    FILE_COMPILATION_CONF,
    FILE_COMPILATION_DUMMY_SPEC,
    FILE_ERC7201_SPEC,
    SUMMARIES_SUBDIR,
)


def user_conf_path(project_root: Path, contract: str) -> Path:
    return project_root / DIR_USER_CONFS / f"{contract}.conf"


def user_sanity_spec_path(project_root: Path, contract: str) -> Path:
    """User-facing entry-point spec at certora/specs/sanity-{contract}.spec.

    Generated by autosetup with the bundled rule sanity body and direct imports
    of the summary aggregator, call-resolution, and (when applicable) erc7201 specs.
    Skip-if-exists after first run so user-added rules survive re-runs."""
    return project_root / DIR_USER_SPECS / f"sanity-{contract}.spec"


def user_call_resolution_spec_path(project_root: Path, contract: str) -> Path:
    """Auto-generated call-resolution / linking spec under certora/specs/summaries/."""
    return project_root / DIR_USER_CERTORA / SUMMARIES_SUBDIR / f"{contract}_call_resolution.spec"


def user_erc7201_spec_path(project_root: Path) -> Path:
    return project_root / DIR_USER_SPECS / FILE_ERC7201_SPEC


def user_harnesses_dir(project_root: Path) -> Path:
    """Directory where autosetup writes generated harness contracts.
    """
    return project_root / DIR_USER_HARNESSES


def user_harness_path(project_root: Path, harness_name: str) -> Path:
    """Path of a single generated harness file under ``certora/harnesses/``.
    ``harness_name`` is the contract name (without ``.sol``)
    """
    return user_harnesses_dir(project_root) / f"{harness_name}.sol"


def internal_warmup_spec(project_root: Path, contract: str) -> Path:
    return project_root / DIR_INTERNAL_SPECS / f"warmup-{contract}.spec"


def internal_compilation_conf(project_root: Path) -> Path:
    return project_root / DIR_INTERNAL_CONFS / FILE_COMPILATION_CONF


def internal_compilation_dummy_spec(project_root: Path) -> Path:
    return project_root / DIR_INTERNAL_SPECS / FILE_COMPILATION_DUMMY_SPEC


def internal_test_compilation_conf(project_root: Path, contract: str) -> Path:
    return project_root / DIR_INTERNAL_CONFS / f"test_compilation-{contract}.conf"


def internal_typechecker_round_dir(project_root: Path) -> Path:
    return project_root / DIR_INTERNAL_TYPECHECKER_ROUNDS


def internal_round_summaries_dir(project_root: Path) -> Path:
    return project_root / DIR_INTERNAL_ROUND_SUMMARIES


def internal_multi_assert_dir(project_root: Path) -> Path:
    return project_root / DIR_INTERNAL_MULTI_ASSERT


def internal_difficult_retry_dir(project_root: Path) -> Path:
    return project_root / DIR_INTERNAL_DIFFICULT_RETRY
