#!/usr/bin/env python3
"""
Parser for all_methods.json file generated by orchestrator.

This parser provides utilities to read and query method information
extracted from compiled contracts.
"""

import json
from pathlib import Path
from typing import List, Dict, Optional, Set


class MethodParser:
    """Parser for all_methods.json file."""
    
    def __init__(self, json_path: Optional[str] = None):
        """Initialize the parser with the path to all_methods.json."""
        if json_path is None:
            json_path = ".certora_internal/all_methods.json"
        self.json_path = Path(json_path)
        self.methods: list[dict] = []
        self.load_methods()
    
    def load_methods(self) -> None:
        """Load methods from the JSON file."""
        if not self.json_path.exists():
            raise FileNotFoundError(f"Methods file not found: {self.json_path}")
        
        with open(self.json_path, 'r') as f:
            self.methods = json.load(f)
    
    def get_all_methods(self) -> List[Dict]:
        """Return all methods."""
        return self.methods
    
    def get_methods_by_contract(self, contract_name: str) -> List[Dict]:
        """Get all methods for a specific contract."""
        return [m for m in self.methods if m['contractName'] == contract_name]

    def get_methods_by_originating_contract(self, contract_name: str) -> List[Dict]:
        """Get all methods that originate from a specific contract (compilation unit)."""
        return [m for m in self.methods if m.get('originatingContract') == contract_name]

    def get_methods_by_name(self, method_name: str) -> List[Dict]:
        """Get all methods with a specific name across all contracts."""
        return [m for m in self.methods if m['name'] == method_name]
    
    def get_methods_by_visibility(self, visibility: str) -> List[Dict]:
        """Get all methods with a specific visibility (public, external, internal, private)."""
        return [m for m in self.methods if m['visibility'] == visibility]
    
    def get_external_methods(self, contract_name: Optional[str] = None) -> List[Dict]:
        """Get all external methods, optionally filtered by contract."""
        methods = [m for m in self.methods if m['visibility'] == 'external']
        if contract_name:
            methods = [m for m in methods if m['contractName'] == contract_name]
        return methods
    
    def get_public_methods(self, contract_name: Optional[str] = None) -> List[Dict]:
        """Get all public methods, optionally filtered by contract."""
        methods = [m for m in self.methods if m['visibility'] == 'public']
        if contract_name:
            methods = [m for m in methods if m['contractName'] == contract_name]
        return methods
    
    def get_payable_methods(self, contract_name: Optional[str] = None) -> List[Dict]:
        """Get all payable methods, optionally filtered by contract."""
        methods = [m for m in self.methods if m['stateMutability'] == 'payable']
        if contract_name:
            methods = [m for m in methods if m['contractName'] == contract_name]
        return methods
    
    def get_view_methods(self, contract_name: Optional[str] = None) -> List[Dict]:
        """Get all view methods, optionally filtered by contract."""
        methods = [m for m in self.methods if m['stateMutability'] == 'view']
        if contract_name:
            methods = [m for m in methods if m['contractName'] == contract_name]
        return methods
    
    def get_pure_methods(self, contract_name: Optional[str] = None) -> List[Dict]:
        """Get all pure methods, optionally filtered by contract."""
        methods = [m for m in self.methods if m['stateMutability'] == 'pure']
        if contract_name:
            methods = [m for m in methods if m['contractName'] == contract_name]
        return methods
    
    def get_library_methods(self) -> List[Dict]:
        """Get all methods from libraries."""
        return [m for m in self.methods if m.get('isLibrary', False)]

    def get_contract_names(self) -> Set[str]:
        """Get a set of all contract names."""
        return set(m['contractName'] for m in self.methods)

    def get_all_contract_names(self) -> List[str]:
        """Get all unique contract names as a sorted list."""
        return sorted(set(m['contractName'] for m in self.methods))
    
    def get_method_signatures(self, contract_name: str) -> List[str]:
        """Get simplified signatures for all methods in a contract."""
        methods = self.get_methods_by_contract(contract_name)
        signatures = []
        for m in methods:
            sig = f"{m['name']}({m['visibility']}"
            if m['stateMutability']:
                sig += f", {m['stateMutability']}"
            sig += ")"
            signatures.append(sig)
        return signatures
    
    def has_method(self, contract_name: str, method_name: str, 
                   visibility: Optional[str] = None,
                   state_mutability: Optional[str] = None) -> bool:
        """Check if a contract has a specific method with optional filters."""
        methods = [m for m in self.methods 
                  if m['contractName'] == contract_name and m['name'] == method_name]
        
        if visibility:
            methods = [m for m in methods if m['visibility'] == visibility]
        
        if state_mutability:
            methods = [m for m in methods if m['stateMutability'] == state_mutability]
        
        return len(methods) > 0
    
    def find_method(self, contract_name: str, method_name: str,
                   visibility: Optional[str] = None,
                   state_mutability: Optional[str] = None) -> Optional[Dict]:
        """Find a specific method, returns first match or None."""
        methods = [m for m in self.methods 
                  if m['contractName'] == contract_name and m['name'] == method_name]
        
        if visibility:
            methods = [m for m in methods if m['visibility'] == visibility]
        
        if state_mutability:
            methods = [m for m in methods if m['stateMutability'] == state_mutability]
        
        return methods[0] if methods else None
    
    def print_summary(self) -> None:
        """Print a summary of the loaded methods."""
        contracts = self.get_contract_names()
        print(f"Total methods: {len(self.methods)}")
        print(f"Total contracts: {len(contracts)}")
        print(f"Libraries: {len([c for c in contracts if any(m['isLibrary'] for m in self.get_methods_by_contract(c))])}")
        print(f"External methods: {len(self.get_external_methods())}")
        print(f"Public methods: {len(self.get_public_methods())}")
        print(f"Payable methods: {len(self.get_payable_methods())}")
        print(f"View methods: {len(self.get_view_methods())}")
        print(f"Pure methods: {len(self.get_pure_methods())}")


def main():
    """Example usage of the MethodParser."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Parse and query all_methods.json")
    parser.add_argument(
        '--file',
        default='.certora_internal/all_methods.json',
        help='Path to all_methods.json file'
    )
    parser.add_argument(
        '--contract',
        help='Filter by contract name'
    )
    parser.add_argument(
        '--method',
        help='Filter by method name'
    )
    parser.add_argument(
        '--visibility',
        choices=['public', 'external', 'internal', 'private'],
        help='Filter by visibility'
    )
    parser.add_argument(
        '--summary',
        action='store_true',
        help='Print summary statistics'
    )
    parser.add_argument(
        '--external',
        action='store_true',
        help='Show only external methods'
    )

    args = parser.parse_args()

    try:
        mp = MethodParser(args.file)

        if args.summary:
            mp.print_summary()
            return

        # Apply filters
        methods = mp.get_all_methods()

        if args.contract:
            methods = [m for m in methods if m['contractName'] == args.contract]

        if args.method:
            methods = [m for m in methods if m['name'] == args.method]

        if args.visibility:
            methods = [m for m in methods if m['visibility'] == args.visibility]

        if args.external:
            methods = [m for m in methods if m['visibility'] == 'external']

        # Print results
        if not methods:
            print("No methods found matching the criteria.")
        else:
            print(f"Found {len(methods)} methods:")
            for m in methods:
                print(f"  {m['contractName']}.{m['name']} ({m['visibility']}, {m['stateMutability']})")
                if m['isLibrary']:
                    print(f"    [Library]")
    
    except FileNotFoundError as e:
        print(f"Error: {e}")
        print("Make sure to run the orchestrator with compilation analysis first.")
        return 1
    except Exception as e:
        print(f"Error: {e}")
        return 1


if __name__ == "__main__":
    exit(main() or 0)