name: pyright-check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          cache-suffix: pyright
      
      - name: sync-deps
        run: |
          uv sync --group ci
          uv pip install sentence_transformers --no-deps

      - name: Run pyright
        run: |
          uv run pyright composer/ analyzer sanity_analyzer certora_autosetup
